CREATE TABLE items (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO items (name) VALUES
('ammo_belt'),
('ammo_bfg'),
('ammo_bullets'),
('ammo_cells'),
('ammo_grenades'),
('ammo_lightning'),
('ammo_mines'),
('ammo_nails'),
('ammo_rockets'),
('ammo_shells'),
('ammo_slugs'),
('holdable_invulnerability'),
('holdable_kamikaze'),
('holdable_medkit'),
('holdable_portal'),
('holdable_teleporter'),
('item_ammoregen'),
('item_armor_body'),
('item_armor_combat'),
('item_armor_shard'),
('item_bluecube'),
('item_doubler'),
('item_enviro'),
('item_flight'),
('item_guard'),
('item_haste'),
('item_health'),
('item_health_large'),
('item_health_mega'),
('item_health_small'),
('item_invis'),
('item_quad'),
('item_redcube'),
('item_regen'),
('item_scout'),
('team_CTF_blueflag'),
('team_CTF_neutralflag'),
('team_CTF_redflag'),
('weapon_bfg'),
('weapon_chaingun'),
('weapon_gauntlet'),
('weapon_grapplinghook'),
('weapon_grenadelauncher'),
('weapon_lightning'),
('weapon_machinegun'),
('weapon_nailgun'),
('weapon_plasmagun'),
('weapon_prox_launcher'),
('weapon_railgun'),
('weapon_rocketlauncher'),
('weapon_shotgun');
