-- Create weapons table
CREATE TABLE IF NOT EXISTS weapons (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- Insert weapons (alphabetically sorted)
INSERT INTO weapons (name) VALUES
('MOD_SHOTGUN'),
('MOD_GAUNTLET'),
('MOD_MACHINEGUN'),
('MOD_GRENADE'),
('MOD_GRENADE_SPLASH'),
('MOD_ROCKET'),
('MOD_ROCKET_SPLASH'),
('MOD_PLASMA'),
('MOD_PLASMA_SPLASH'),
('MOD_RAILGUN'),
('MOD_LIGHTNING'),
('MOD_BFG'),
('MOD_BFG_SPLASH'),
('MOD_WATER'),
('MOD_SLIME'),
('MOD_LAVA'),
('MOD_CRUSH'),
('MOD_TELEFRAG'),
('MOD_FALLING'),
('MOD_SUICIDE'),
('MOD_TARGET_LASER'),
('MOD_TRIGGER_HURT');
